### ISSUE TITLE
Vim/Neovim version, please?

### ISSUE THREAD

**Issue by kassio** [VitorNoVictor/capitola#1]
This is looking really good. Any plans to add a vim/neovim version?

Thanks! ❤️💛💚💜💙🖤🧡

**Comment by vtr44** [comment]
Thank you for being so supportive, my dear friend :heart: @kassio :heart: 

I plan to create versions for Vim/Neovim, JetBrains' IDEs, and some major terminal emulators like Alacritty.

I'll keep you posted :)
